---
abstract: 'Data utilities'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SHARYANTO-Data-Util
requires:
  Data::Clone: 0
  Data::Structure::Util: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/SHARYANTO-Data-Util/
  repository: http://github.com/sharyanto/perl-SHARYANTO-Data-Util
version: 0.56
